# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: AzureResourceManagerTemplateDeployment@3
  inputs:
    deploymentScope: 'Resource Group'
    azureResourceManagerConnection: 'DocsPipelineDemo-ServiceConnection'
    subscriptionId: '5431caeb-4932-47a6-b753-42903a17fed2'
    action: 'Create Or Update Resource Group'
    resourceGroupName: 'labnet1'
    location: 'West Europe'
    templateLocation: 'Linked artifact'
    csmFile: 'template.json'
    csmParametersFile: 'parameters.json'
    deploymentMode: 'Incremental'

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'
